apiVersion: v1
kind: Service
metadata:
    name: appname 
    labels:
        app: appname
spec:
    type: LoadBalancer
    loadBalancerSourceRanges:
    # Here is where you whitelist IPs to connect to balancer while testing 
    #- 8.8.8.8/32
    #- 1.3.3.7/24
    #- etc.
    ports:
    - port: 80
      targetPort: 8080
    selector:
        app: appname
