apiVersion: v1
kind: ConfigMap
metadata:
    name: gitlab-runner
    namespace: appname-testing
data:
    config.toml: |
        concurrent = 4
        log_level = "debug"

        [[runners]]
            name = "appname-testing"
            url = "<gitlab_project_url>"
            token = "<gitlab_runner_token>"
            executor = "kubernetes"
            [runners.kubernetes]
                namespace = "appname-testing"

